### ISSUE TITLE
Autolink removes text when the link isn't prefixed with http(s)://

### ISSUE THREAD

**Issue by kevinrenskers** [objecthub/swift-markdownkit#4]
If I try to parse this markdown to html, then the entire link is removed.

```
Test <www.example.com> test
```

I'd expect that it turns it into a valid link, or failing that, at least doesn't remove the text?

**Comment by objecthub** [comment]
Thanks a lot for filing this bug. According to the Commonmark spec, autolinks are absolute URIs and email addresses inside `<` and `>`. According to this definition, `<www.example.com>` is not an autolink and thus should be rendered as is, including the angle brackets. And this is where the problem lies: The generated HTML is not encoding `<` and `>` correctly and thus `<www.example.com>` is written just like an HTML tag and thus dropped by the HTML renderer.

**Comment by objecthub** [comment]
This is now fixed with my latest [commit](https://github.com/objecthub/swift-markdownkit/commit/8298e1d35f0899366c62234441bd451c8c8e4fd5).
